modify the configmap data for argocd
viaduct-ai/kustomize-sops pull request #105
Opened 2021-04-09 09:14 UTC by majinghe

If the configmap data is `--enable-alpha-plugins` instead of `--enable_alpha_plugins`,will show error ```Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `kustomize build /tmp/https:__github.ibm.com_crmk8sdevops_devops4newco/helm-charts/kustomize/apim/overlays/svt --enable-alpha-plugins` failed exit status 1: Error: unknown flag: --enable-alpha-plugins``` when using kops with argocd.

2021-04-09 09:15 UTC, majinghe commented
corresponding issue is #104

2021-04-10 00:17 UTC, devstein requested changes
Please see my comment in the [issue](https://github.com/viaduct-ai/kustomize-sops/issues/104#issuecomment-817037565)

2021-04-17 01:55 UTC, majinghe commented
@devstein  according to your suggestion, i have updated the PR info. Please help to have a check.

2021-04-18 22:56 UTC, devstein approved these changes
Thanks for contributing!

2021-04-18 22:56 UTC, merged